//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopData
{
    using System;
    using System.Collections.Generic;

    public class Good
    {
        public int GoodId { get; set; }

        public string GoodName { get; set; }

        public string Manufacturer { get; set; }

        public string Category { get; set; }

        public decimal Price { get; set; }

        public int GoodCount { get; set; }

        public string Photo { get; set; }
    }
}
